ALTER TABLE users ALTER COLUMN id TYPE BIGINT;

ALTER TABLE categories ALTER COLUMN id TYPE BIGINT;
ALTER TABLE categories ALTER COLUMN created_by TYPE BIGINT;

ALTER TABLE groups ALTER COLUMN id TYPE BIGINT;
ALTER TABLE groups ALTER COLUMN created_by TYPE BIGINT;

ALTER TABLE group_members ALTER COLUMN group_id TYPE BIGINT;
ALTER TABLE group_members ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE group_members ALTER COLUMN invited_by TYPE BIGINT;

ALTER TABLE friendships ALTER COLUMN id TYPE BIGINT;
ALTER TABLE friendships ALTER COLUMN requester_id TYPE BIGINT;
ALTER TABLE friendships ALTER COLUMN addressee_id TYPE BIGINT;

ALTER TABLE expenses ALTER COLUMN id TYPE BIGINT;
ALTER TABLE expenses ALTER COLUMN group_id TYPE BIGINT;
ALTER TABLE expenses ALTER COLUMN paid_by_user_id TYPE BIGINT;
ALTER TABLE expenses ALTER COLUMN category_id TYPE BIGINT;

ALTER TABLE splits ALTER COLUMN id TYPE BIGINT;
ALTER TABLE splits ALTER COLUMN expense_id TYPE BIGINT;
ALTER TABLE splits ALTER COLUMN user_id TYPE BIGINT;

ALTER TABLE settlements ALTER COLUMN id TYPE BIGINT;
ALTER TABLE settlements ALTER COLUMN group_id TYPE BIGINT;
ALTER TABLE settlements ALTER COLUMN paid_by_user_id TYPE BIGINT;
ALTER TABLE settlements ALTER COLUMN paid_to_user_id TYPE BIGINT;

ALTER TABLE notifications ALTER COLUMN id TYPE BIGINT;
ALTER TABLE notifications ALTER COLUMN user_id TYPE BIGINT;
ALTER TABLE notifications ALTER COLUMN reference_id TYPE BIGINT;

ALTER TABLE categories ADD COLUMN color VARCHAR(20);
ALTER TABLE categories ADD COLUMN created_at TIMESTAMP DEFAULT now();
ALTER TABLE categories ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE categories RENAME COLUMN is_global TO is_default;
